### ISSUE TITLE
Ability to pass user data as a parameter.

### ISSUE THREAD

**Issue by mhussain** [envato/stack_master#104]
Requesting the ability to pass user data as parameter to the stack instead of having to write in inline in the template.

Something like

``` yaml
DateInit: files/user_data.txt
```

``` json
"DataInit": {
  "Type": "String",
  "Description": "Initialisation script"
}
...

"UserData": { "Fn::Base64": { "Ref": "DataInit" } }

...
```

**Comment by simpsora** [comment]
:+1: to this idea -- it would be nice to have UserData content extracted to a separate file.

For this to be most useful, the content of the would still need to be parsed by CloudFormation, in order to resolve intrinsic functions (`Fn::Ref`, `Fn::GetAtt`, etc.).  Use of those functions may introduce some strange requirements when it comes to quoting the content.

**Comment by stevehodgkiss** [comment]
I saw an interesting solution to this in a sparkleformation issue: https://github.com/sparkleformation/sparkle_formation/issues/54#issuecomment-143136818

It enables separate user data files while being able to use ERB to call sparkle functions inside that file like `<%= region! %>`.

**Comment by simpsora** [comment]
@stevehodgkiss that's an interesting approach, although it's a shame that it only works with Sparkle.  I'd love to see a more generic approach if possible (though I don't currently see how).

`cloud-init` has quite a bit more functionality than just user-data shell scripts, see here:
https://help.ubuntu.com/community/CloudInit

About the only idea I have is to create a grammar of some kind to allow embedding CF references/functions inline in the script, then replacing them with closequote-var-openquote:
```...", { "Ref" : "Foo" }, "...```

**Comment by simpsora** [comment]
@mhussain: 0.6.0 has been released, which contains `user_data_file!`.  See https://github.com/envato/stack_master/pull/117 for details.

**Comment by stevehodgkiss** [comment]
I think the approach/code used in #117 could be used in JSON/YAML templates quite easily too, we'd just need to run it through the same Erubis context. It could look like this:

```
  "UserData": <%= user_data_file!('app.erb') %>
```
