### ISSUE TITLE
Would love to be able to get stack_master to prompt for parameter values at run time

### ISSUE THREAD

**Issue by andrewjhumphrey** [envato/stack_master#105]
I'd like to be able to commit example stacks that folks can use without modification, but some of the parameters refer to other stacks.  The simplest way I can think of is to be able to market a parameter as needing to be requested from the user at run time.  If it's overriden in a more specific parameter file then don't prompt.

Something like:

```
# parameters/foo.yml
foo_id:
  request_if_required: true
```

Would prompt when the template is compiled or applied, but if the file below existed it would use the value from it instead of prompting:

```
# paramters/us-east-1/foo.yml
foo_id: x-12312312321
```

**Comment by stevehodgkiss** [comment]
This could be implemented as a parameter resolver with the way things currently work.

**Comment by patrobinson** [comment]
You can now export them as Environment variables, is that sufficient?
