### ISSUE TITLE
Feature request:  stack_master.yml is a pest with multiple PRs in play

### ISSUE THREAD

**Issue by andrewjhumphrey** [envato/stack_master#106]
Lots of folks adding to a stack_master.yml makes for much merge hassle. 

Maybe this could be "solved" by making convering stack_master.yml to a stack_master.d directory and merging all the files that are found in there.

I guess regularly merging origin/master back into your branch would do the same thing but for long lived PRs that's a bit of a pest just to pick up new stacks others have created.

**Comment by flyinbutrs** [comment]
I have a PR ready that has similar functionality, but not quite. I.E. it creates a stacks directory, and each yaml in that folder is named the region / region alias, and is combined that way. Would that satisfy your needs, or do you need multiple files to source into the same region / alias? If the latter, how would you propose resolving duplicate declarations? Raise an error?

**Comment by andrewjhumphrey** [comment]
@flyinbutrs Neat! It would be an improvement over the one file to rule them all mode at the moment, but I had something quite simple in mind, literally just cat together all the files found in the directory and use standard yaml semantics to deal with duplicates (ie last loaded wins).  Raising an error on duplicates makes sense though.   One of the things that I lean a lot on in sparkleformation are dynamics,  a bunch of directories would make them a bit harder to deal with wouldn't it?

**Comment by flyinbutrs** [comment]
I haven't really used sparkleformation yet, though I definitely want to.  Why would multiple directories make using dynamics in SF harder?

If it were just a series of load/merges, how would you settle on a load order? That seems like a recipe for bad things. I was sort of thinking that each file would be the region/alias, but could pretty easily do multiple folders with region/alias yamls, and then merge those. I'm not sure what makes the most sense though.  And of course, this isn't my project, so I think @stevehodgkiss would have to way in anyway.

**Comment by andrewjhumphrey** [comment]
The search path for dynamics in sparkle is tied to the template and changing it is.... entertaining :-)

The normal unix practice for this sort of thing is just straight ascii lexicographical order, more or less the same order that ls outputs.   It's a convention over configuration thing more than anything else.

I think the multiple folkds with region/alias is sort of converging to where my head was it. So okay @stevehodgkiss we've more or less decided what we want, make it so please ;-P

**Comment by patrobinson** [comment]
I think this is better supported now with #161 Can we close it @andrewjhumphrey ?

**Comment by andrewjhumphrey** [comment]
@patrobinson Yep, that will scratch my itch nicely.
