### ISSUE TITLE
[Feature request] Support search tags that do not have value for AMI lookup

### ISSUE THREAD

**Issue by joneslee85** [envato/stack_master#114]
# What is this about?

It is a good practice to use the `latest_ami_by_tags` feature to look up one AMI by its tag. For example:

```
web_ami:
  latest_ami_by_tags: role=web,application=myapp
```

However I learn that if you have a tag pair that has no value and the stack definition you omit the value part, the parser would error:

```
web_ami:
  latest_ami_by_tags: a_valueless_tag
```

It would be nice if the above format is accepted

**Comment by patrobinson** [comment]
As a workaround this will probably work:

```
web_ami:
  latest_ami:
    filters:
      tag:a_valueless_tag: ""
```
