### ISSUE TITLE
Stack exists but output does not.

### ISSUE THREAD

**Issue by visualne** [envato/stack_master#116]
Anyone know what I am doing wrong here....I keep getting the following error when I run the following command "stack_master apply --trace" I have two stacks...test and test2

/home/centos/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/stack_master-0.5.0/lib/stack_master/parameter_resolvers/stack_output.rb:24:in `resolve': Stack exists (test), but output does not: testVar (StackMaster::ParameterResolvers::StackOutput::StackOutputNotFound)

Why do I see testVar when I do: "stack_master outputs us-east-1 test --trace"?

*****************************************************
*The below is in the template (test.yaml) I want to get it from....
  "Outputs" : {
    "testVar" : {
      "Description" : "Test Variable",
      "Value" : "TESTDATA"
    }
  }

In my parameters file for my second template I am referencing it as follows
testVar2:
    stack_output: test/testVar

On my second template I am I referencing testVar2 as follows
  Parameters section
      "testVar2" : {
      "Type" : "String",
      "Description" : "Test variable that is read from the output of the test template."
    }
      
Under tags section of EC2Instance
"Tags": [
          { "Key": "Name", "Value": {"Ref": "testVar2" } }
        ]

**Comment by patrobinson** [comment]
Have you applied the `test` stack with the changes?

If you update a stack with just some output, it won't actually update.

**Comment by visualne** [comment]
My fault. I wasn't referencing the parameter correctly.
