### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by jrudge-kcom** [envato/stack_master#134]
Hi,

I really want to give stack_master a go however I am having trouble installing the gem on windows. I am running gem 2.6.7 and it pulls down all the dependencies however when it gets to "building native extensions"  it errors. I have looked at the logs but I am unable to work out what is wrong, I am not that familiar with ruby. Can you help at all? I have tried it on 3 systems, windows 7 and windows 10 with the same result.

ERROR:  Error installing stack_master:
        ERROR: Failed to build gem native extension.

```
current directory: N:/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12/ext/gpgme
```

N:/Ruby23/bin/ruby.exe -r ./siteconf20161013-1180-gq47yd.rb extconf.rb

---

IMPORTANT!  gpgme gem uses locally built versions of required C libraries,
namely libgpg-error, libassuan, and gpgme.

If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall gpgme gem as
follows:

```
gem install gpgme -- --use-system-libraries
```

---

Extracting libgpg-error-1.21.tar.bz2 into tmp/i686-w64-mingw32/ports/libgpg-error/1.21... OK
Running 'configure' for libgpg-error 1.21... OK
Running 'compile' for libgpg-error 1.21... ERROR, review 'N:/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12/ext/gpgme/tmp/
# i686-w64-mingw32/ports/libgpg-error/1.21/compile.log' to see what happened. Last lines are:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DLOCALEDIR=\"N:/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12/ports/i686
-w64-mingw32/libgpg-error/1.21/share/locale\" -fPIC -Wall -Wpointer-arith -Wno-psabi -MT libgpg_error_la-estream.lo -MD
-MP -MF .deps/libgpg_error_la-estream.Tpo -c estream.c -o libgpg_error_la-estream.o
estream.c:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]
estream.c: In function 'es_fill':
estream.c:1714:24: error: 'EWOULDBLOCK' undeclared (first use in this function)
estream.c:1714:24: note: each undeclared identifier is reported only once for each function it appears in
estream.c: In function 'es_flush':
estream.c:1784:28: error: 'EWOULDBLOCK' undeclared (first use in this function)
estream.c: In function 'es_read_nbf':
estream.c:2044:24: error: 'EWOULDBLOCK' undeclared (first use in this function)
estream.c: In function 'es_seek':
estream.c:2316:20: error: 'EWOULDBLOCK' undeclared (first use in this function)
estream.c: In function 'es_write_nbf':
estream.c:2374:24: error: 'EWOULDBLOCK' undeclared (first use in this function)
make[3]: **\* [libgpg_error_la-estream.lo] Error 1
make[3]: Leaving directory `/n/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12/ext/gpgme/tmp/i686-w64-mingw32/ports/libgpg-
error/1.21/libgpg-error-1.21/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory`/n/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12/ext/gpgme/tmp/i686-w64-mingw32/ports/libgpg-
error/1.21/libgpg-error-1.21/src'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/n/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12/ext/gpgme/tmp/i686-w64-mingw32/ports/libgpg-
error/1.21/libgpg-error-1.21'
# make: **\* [all] Error 2

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=N:/Ruby23/bin/$(RUBY_BASE_NAME)
        --clean
        --use-system-libraries
N:/Ruby23/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in `block in execute': Fail
ed to complete compile task (RuntimeError)
        from N:/Ruby23/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in`chdir'
        from N:/Ruby23/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in `execute'
        from N:/Ruby23/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:111:in`compile'
        from N:/Ruby23/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:150:in `cook'
        from extconf.rb:76:in`block in <main>'
        from extconf.rb:65:in `tap'
        from extconf.rb:65:in`<main>'

extconf failed, exit code 1

Gem files will remain installed in N:/Ruby23/lib/ruby/gems/2.3.0/gems/gpgme-2.0.12 for inspection.
Results logged to N:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/gpgme-2.0.12/gem_make.out

**Comment by patrobinson** [comment]
gpgme doesn't seem to support WIndows out of the box, which means we also can't support windows. I found this issue https://github.com/ueno/ruby-gpgme/issues/81 reporting the same problem.

I wonder if we can make installing gpgme optional and only support secrets on Unix environments cc @stevehodgkiss ?

**Comment by zeldigas** [comment]
@jrudge-kcom probably you can go with docker. I created image with stack_master: https://hub.docker.com/r/zeldigas/stack_master/

**Comment by jrudge-kcom** [comment]
Thanks. I will give that a go.
