### ISSUE TITLE
InsufficientCapabilitiesException Requires capabilities : [CAPABILITY_NAMED_IAM]

### ISSUE THREAD

**Issue by breezeight** [envato/stack_master#138]
My cloudformation stack require CAPABILITY_NAMED_IAM, I'm getting this error:

```
Aws::CloudFormation::Errors::InsufficientCapabilitiesException Requires capabilities : [CAPABILITY_NAMED_IAM]
```

It looks like the capability param is hardcoded https://github.com/envato/stack_master/blob/master/lib/stack_master/commands/apply.rb#L124

**Comment by patrobinson** [comment]
I've released 0.9.0 which allows using named IAM resources
