### ISSUE TITLE
How to access parameters??

### ISSUE THREAD

**Issue by discobean** [envato/stack_master#159]
Hi,

I've been going through the templates and examples, and for the life of me I don't know how to reference parameters (parameters/*.yml) from a yml or json CF template file (templates/*)?

**Comment by patrobinson** [comment]
Wow I totally missed this Issue.

You can reference parameters just like normal [CloudFormation parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html). But the convention is you convert the CamelCase parameter name in the template to `snake_case` when defining it in the parameter file
