### ISSUE TITLE
Support for optional parameters

### ISSUE THREAD

**Issue by berniedurfee-ge** [envato/stack_master#164]
Cloudformation allows parameters to be optional by using a conditional in the template:

https://cloudonaut.io/optional-parameter-in-cloudformation/

Though, it appears because Stack Master checks for empty parameters, it won't allow the use of conditions to create optional parameters.

Seems like without actually evaluating the conditions in a template, it would be difficult to evaluate when a parameters is being treated as optional.

Is there an easier way? Maybe a annotation in the stack_master.yml file to allow a stack to be submitted even when there appear to be empty parameters?

**Comment by patrobinson** [comment]
A couple of ways you can achieve this:

- Set the Default to `""` in the template
- Set the parameter to `""` in the parameter yml file.

Let me know if this doesn't work for you.
