### ISSUE TITLE
Automatic tag with template's filesystem path

### ISSUE THREAD

**Issue by simpsora** [envato/stack_master#166]
In an organization with multiple SCM repositories and stacks defined all over the place, it can be hard to know where the source for a stack lives, looking at the stack itself.

Add a new tag to the stack which contains the fully-expanded path to the template file which created the stack.

For example:

```
Key = template_source
Value = /Users/rosssimpson/src/aws/templates/ntp.rb
```

If git would just support `$Header$` this wouldn't be a problem! :)

**Comment by patrobinson** [comment]
As discussed this is probably better attacked with a good tagging strategy.
