### ISSUE TITLE
Specifying a config file moves the project root

### ISSUE THREAD

**Issue by arecker** [envato/stack_master#172]
StackMaster always expects the templates folder to be in the same directory as the stack master config.

To reproduce:

```
├── Gemfile
├── Gemfile.lock
├── configs
│   └── stack_master.yml
├── parameters
│   ├── mystack.yml
│   └── us-west-2
│       └── mystack.yml
└── templates
    └── mystack.json
```

```
arecker@localhost:testproject$ bundle exec stack_master diff -c configs/stack_master.yml 
Executing diff on mystack in us-west-2
StackMaster::TemplateCompiler::TemplateCompilationFailed Failed to compile /Users/arecker/Desktop/testproject/configs/templates/mystack.json.
 Caused by: Errno::ENOENT No such file or directory @ rb_sysopen - /Users/arecker/Desktop/testproject/configs/templates/mystack.json
```

**Comment by patrobinson** [comment]
This is expected behaviour. Do you have a use case for not storing `stack_master.yml` in the top level?

**Comment by arecker** [comment]
Hey Patrick,

We're planning on keeping a lot of configs in the same repository within
a top level "configs" folder.  Cosmetics aside, shouldn't this tool use
the working directory as the project root, rather than getting it from
the path to the stack master config?  Otherwise, the "-c" option is more
like a "--specify-project-root" option.

Hope that makes sense - I haven't had any coffee yet.

**Comment by arecker** [comment]
Ah - now that I look at it, this is probably just another manifestation of #161.

**Comment by patrobinson** [comment]
#161 looks like it might solve your problem. I'll try and roll it out tomorrow (AEST)

**Comment by arecker** [comment]
Great!  You're the best - thanks.
