### ISSUE TITLE
Config level tags are ignored

### ISSUE THREAD

**Issue by arecker** [envato/stack_master#173]
The documentation promises that you can specify stack-level and config-level tags.  Running `stack_master init us-west-2 test-stack` even generates a stack-level tag for you.

```
stacks:
  us-west-2:
    test-stack:
      template: test-stack.json
      tags:
        environment: production
```

However, running `stack_master diff` against the template, the `environment:production` tag is nowhere to be seen.

```
arecker@localhost:testproject$ be stack_master diff
Executing diff on test-stack in us-west-2
Stack diff: 
--- /var/folders/sc/b7xz6j0d57z5_d7j72mzyw800000gp/T/diffy20170411-39386-b6rlc6 2017-04-11 15:39:47.000000000 -0500
+++ /var/folders/sc/b7xz6j0d57z5_d7j72mzyw800000gp/T/diffy20170411-39386-e3a2o7 2017-04-11 15:39:47.000000000 -0500
@@ -0,0 +1,16 @@
+{
+  "AWSTemplateFormatVersion": "2010-09-09",
+  "Description": "Cloudformation stack for test-stack",
+  "Parameters": {
+    "InstanceType": {
+      "Description": "EC2 instance type",
+      "Type": "String"
+    }
+  },
+  "Mappings": {
+  },
+  "Resources": {
+  },
+  "Outputs": {
+  }
+}
\ No newline at end of file
Parameters diff: 
+---
+InstanceType: 
No stack found
```

How are these tags intended to work exactly?  I would have expected any taggable resource in the stack to receive this.  Maybe this feature isn't complete?

**Comment by patrobinson** [comment]
Wow, 1 year for me to reply to this issue. I'm really sorry about that.

The tags exist against the stack itself and hence are not present in the template. CloudFormation then propagates these tags to Resources within the stack where they support it.

Sorry again for taking so long to reply.

**Comment by arecker** [comment]
> Wow, 1 year for me to reply to this issue. I'm really sorry about
> that.

Lol - no worries, mate.  We have since been using stack level tags, and
I should have circled back and closed the issue myself.  Thanks!

**Comment by patrobinson** [comment]
Feel free to join our [slack workspace](https://join.slack.com/t/stackmasteross/shared_invite/enQtMzQ2MTg5MTkwMzA3LTdiY2ZjNTk1MGY4ZmNiZjM3OGIwODkwODE5MzQ3OGJkZTQ3NTUyYmM5NTg5ZjY2YTlkNTdjOTVjZDZkZGE5YmQ) if you have further questions, we should be more responsive there.
