### ISSUE TITLE
Support Serverless Application Model (SAM) templates

### ISSUE THREAD

**Issue by skatsuta** [envato/stack_master#176]
CloudFormation supports [Serverless Application Model (SAM)](https://github.com/awslabs/serverless-application-model) templates, but when we use a SAM template StackMaster returns the following error:

```sh
$ stack_master apply
...
...
No stack found
Create stack (y/n)?
Uploading files to S3:
...
Aws::CloudFormation::Errors::ValidationError CreateStack cannot be used with templates containing Transforms.
```

This is because CreateStack API does not support SAM templates.
Instead, we need to use a change set to create a SAM-based stack.
So it'd be great if StackMaster supports SAM templates.

**Comment by skatsuta** [comment]
Blocker is #177.

**Comment by skatsuta** [comment]
Merging both #178 and #179 will support this feature.

**Comment by patrobinson** [comment]
I've released verison 0.16.0 which includes the above PRs

**Comment by skatsuta** [comment]
Great! I confirmed the version works fine with SAM. Thank you for your support!

**Comment by tanyajajodia** [comment]
Hi @skatsuta - Does StackMaster support the `aws cloudformation package` step as well for SAM templates? 

I get the following error when I try to create a stack directly using `stack_master apply`:
`Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [GraphQL] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.`

**Comment by patrobinson** [comment]
@tanyajajodia sorry for the late reply. No we don't currently support that step, it must be done before StackMaster is invoked.
I'd be happy to include such functionality in the future, at present we are just using plain old SAM, but it'd be nice to directly integrate it with StackMaster.
