### ISSUE TITLE
Create a change set when creating a stack

### ISSUE THREAD

**Issue by skatsuta** [envato/stack_master#177]
Currently StackMaster issues `CloudFormation::Client#create_stack` when creating a stack, while it updates a stack using `CloudFormation::Client#create_change_set` and `#execute_change_set`.
However, [we can also use CreateChangeSet API when creating a stack](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-stacks-changesets.html).
I think it's better to use the API to create a stack because we can confirm all resources to be added by change set details.
In addition, it's required to use CreateChangeSet API to create a stack from a SAM template (So this is a blocker of #176).

I'm willing to implement this feature, but have one concern.
[`CloudFormation::Client#create_stack` can pass a stack policy with `stack_policy_body` or `stack_policy_url` parameters](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#create_stack-instance_method), while [`CloudFormation::Client#create_change_set` cannot](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#create_change_set-instance_method).
So I have two ideas:

1. add another command or additional option in `apply` command to create a stack using a change set
2. always create a stack using a change set and then update the stack when a stack policy exists in `stack_master.yml`

I'd like to hear your ideas and opinions to add (or against) this feature. Thank you.

**Comment by patrobinson** [comment]
When would you need to pass a `stack_policy_body` or url to create_stack?

Can we just `set_policy...` after we apply the change_set?

**Comment by skatsuta** [comment]
Ah brilliant! I haven't noticed we can use `set_stack_policy` to set a stack policy after stack creation.
Now I'll implement this.
