### ISSUE TITLE
Support SparkleFormation compile-time parameters

### ISSUE THREAD

**Issue by simpsora** [envato/stack_master#184]
http://www.sparkleformation.io/docs/sparkle_formation/compile-time-parameters.html

Use case: some resource types expect a particular repetitive data structure, e.g. an array of JSON objects.  There is no suitable existing variable type which supports such a thing.

Enabling compile-time parameters would expose parameters to ruby methods in the DSL, allowing the caller to create the required data structure.

This could be implemented by supporting an additional type of parameters file, whose contents are applied to compile-time parameters rather than the standard parameters.

**Comment by patrobinson** [comment]
Related to #144 (which is for cfndsl)

**Comment by patrobinson** [comment]
Released in 0.18.0
