### ISSUE TITLE
Support YAML for policies

### ISSUE THREAD

**Issue by jqr** [envato/stack_master#188]
It would be nice to be able to write policy documents in the YAML format similar to how you can write templates in JSON and YAML.

**Comment by patrobinson** [comment]
Hi @jqr, from what I've heard this is possible, but I don't think it's something we should implement in StackMaster regardless. StackMaster is not the DSL, it integrates with many DSLs to compile to YAML or JSON, but it doesn't implement it's own DSL.

**Comment by jqr** [comment]
That's fair, but it's worth noting that YAML to JSON is supported  by the Ruby standard Library. In fact, this would be the entirety of the code:

```ruby
JSON.dump(YAML.load_file("file.yml"))
```

**Comment by patrobinson** [comment]
You can use SparkleFormation, which allows arbitrary Ruby code, to do this for you. I recommend that approach over trying to bolt this into StackMaster.

I'm going to close this now, let me know if you have any further questions.
