### ISSUE TITLE
Feature `stack_master check` - diff with non zero exit code if differences detected

### ISSUE THREAD

**Issue by joesustaric** [envato/stack_master#205]
Hello,

Recently we have been doing work on some of our aws stacks using stack_master and have come across some scenarios where stack diff change sets started showing us unexpected changes.
Luckily there was nothing major just tags and some other minor things, but these extra changes just added unnecessary noise to the work we were trying to complete. 
Changes can happen for whatever reason, manual changes, aws changing things, stack definitions that have not been applied.. etc.. 

I was trying to think of how could we detect "stack drift" more effectively and I was contemplating using `stack_master` to help.
I know that there is a `diff` command but I was hoping to somehow automate this via a CI tool that has read only access to our aws accounts.
There are many stacks that get updated infrequently and if they drift for whatever reason it would be great to flag these changes early for review.

So my proposition is something along the lines of
`stack_master check production stack-name`
which would output the diff and exit 0 if no changes and exit 1 if changes were detected.

Does that seem like a useful feature to have in stack_master?

Thanks

**Comment by patrobinson** [comment]
When you say stack drift, do you mean drift from what is in source control vs. what is in AWS? There is already a `stack_master status` command that does this.

If you mean differences between the stack and the actual environment, this is something I'd hope AWS would implement.

**Comment by joesustaric** [comment]
Hey @patrobinson Yeah when code drifts from whats in aws. 
Great I'll play with the `status` command.. I think thats a lot of what I want.. except the non zero exit code. :) 

I might just do a simple grep of the output for a "Yes" afterwards.. 
That might be easiest for now.. 👍
