### ISSUE TITLE
Error when OJ is installed - `TypeError wrong argument type Integer (expected String)`

### ISSUE THREAD

**Issue by stevehodgkiss** [envato/stack_master#214]
I'm running into this error when OJ is used. Uninstalling OJ fixes it.

```
❯ ave [snip] -- stack_master apply us-east-1 [snip] --trace
Executing apply on [snip] in us-east-1
StackMaster::TemplateCompiler::TemplateCompilationFailed Failed to compile [snip].rb.
 Caused by: TypeError wrong argument type Integer (expected String)
❯ gem uninstall oj

You have requested to uninstall the gem:
        oj-3.4.0

Continue with Uninstall? [yN]  y
Successfully uninstalled oj-3.4.0

❯ ave [snip] -- stack_master apply us-east-1 [snip] --trace
Executing apply on sherlock-rds in us-east-1
Stack diff: No changes
[snip - it works]
```

MultiJson will use OJ when it's installed / loadable. It's a dependency of SparkleFormation. Related MultiJson issue - https://github.com/intridea/multi_json/issues/181

Options:

- Configure MultiJson (in StackMaster) to use `JSON` instead of `Oj`.
- Add Oj as a direct dependency of StackMaster & pin it to Oj 2.x

I vote for the first option.

**Comment by petervandoros** [comment]
I agree, Option 1 appears to be more maintainable long term.
