### ISSUE TITLE
Changesets should contain Stack-Name to handle proper IAM-Permissions

### ISSUE THREAD

**Issue by markus7811** [envato/stack_master#223]
Whe running several applications from several devops teams in one account, it is a problem that the changeset-Names start with StackMaster. Instead they should start with StackName+StackMaster+Timestamp or something else.

All of our stacks are created with name convetion ApplicationName--, so i can set my iam prevliiges to 
Resource: "arn:...Stack/${ApplicationName}--*"

With StackMaster as ChangeSet Name it is not possible

**Comment by patrobinson** [comment]
I would support this implementation, it should be fairly trivial to implement.
