### ISSUE TITLE
Please add ability to disable CamelCase for Parameters

### ISSUE THREAD

**Issue by markus7811** [envato/stack_master#234]
Hi,
in sparkleformation it is possible to disable camel case. Please add the ability to do the same for parameter files. It sould be possible, that you define parameters like MY_FANCY_ENVIRONMENT_VARIABLE ... and i don't want that to be MYFancyEnvironmentVariable.

**Comment by patrobinson** [comment]
👍 I wonder if this setting should live in stack_master.yml or the parameter file?

**Comment by rbayerl** [comment]
I don't understand. Which part of the parameter is being converted? I don't think you can have a parameter named "MY_PARAMETER" . That isn't valid cloudformation afaik.

**Comment by markus7811** [comment]
ok - let me think it over again ^^

**Comment by rbayerl** [comment]
Can you give an example of what isn't working and how you'd like it to work? Maybe I'm just not following what you're asking for 🙂

**Comment by markus7811** [comment]
You are right - my fault:

I validated a template that was like i wanted to ....

Template contains errors.: Template format error: Parameter name ENV_TEST_PARAMETER is non alphanumeric.
