### ISSUE TITLE
Ability to use several parameter files per stack

### ISSUE THREAD

**Issue by markus7811** [envato/stack_master#236]
It would be nice if there would be an option to use several parameter files: 

Our stacks belong to an application and an environmet - so i have a lot of parameters that are identical for the whole application (and all their stacks), some are the same for each stack of an environment and only some are stack specific. 

So it would be nice to have a parameter file for all parameters that are shared by all stacks for the application, the environment and then for each stack. They could simple be merged together. 

I thought of a custom parameter resolver for this - but i think merging them together would be more easy.

**Comment by patrobinson** [comment]
This behaviour reminds me of [Puppet's Hiera](https://puppet.com/docs/puppet/5.4/hiera_intro.html) implementation and I have a lot of opinions about that so bare with me :)

Firstly, it obscures the final value in use, such that it's not obvious (short of running the command) what the resulting value is. I would prefer, for improved experience of the software from someone unfamiliar with how things are setup, that the parameter in use is obvious.

That does not mean though we cannot add some kind of "pointer" though. If some value is re-used a lot, pointing to some "constant" value in another parameter file seems logical and easy for a person unfamiliar with the environment to follow.

**Comment by orien** [comment]
Since version 2.7.0 and added in #338, StackMaster provides the ability to explicitly specify multiple parameter files for a given stack in the `stack_master.yml` configuration file. This explicit definition will allow you to configure your stacks and share parameter files as you have suggested.
