### ISSUE TITLE
Ability to set a timeout for cloudformation updates

### ISSUE THREAD

**Issue by markus7811** [envato/stack_master#237]
If you use Cloudformation to deploy for example ECS Services, it works really nice! But if you have a failure within your docker image or your configuration and your container won't become healthy, cloudformation will try to get up the new container till it runs in its own timeout. 

But this timeout is about 3 hrs in my case. About 100 containers started and failed in this case. 

It would be nice to add a timeout per stack you can configure and if the cloudformation update process takes longer than a customizable timeout, it should call the aws api and cancel the update and exit with an code > 0 with message that timeout exceeded.

**Comment by patrobinson** [comment]
My personal opinion is CloudFormation is the wrong choice for deploying containers, and any application, for this precise reason. It does not have the capabilities to define a state machine such "if this thing fails, rollback, or do some other thing". It's very limited (rollback or don't). Cancelling a stack update doesn't always work, you can end up in a state where the old container won't start and you're stuck waiting for the hardcoded 1 hour timeout. When it eventually fails you must delete the whole stack.

Internally we use ruby scripts to orchestrate container deployments.

**Comment by patrobinson** [comment]
As previously stated, I think there are better tools than Cloudformation to deploy containers with and I don't think we should attempt to work around those limitations in StackMaster.
