### ISSUE TITLE
spec.files does not include all necessary dirs

### ISSUE THREAD

**Issue by DanielRedOak** [envato/stack_master#246]
The following change looks to have effectively dropped some of the required files from the resulting Gem. New installs no longer work when trying to do something like a `stack_master init` action since the stacktemplates dir is not included.
  https://github.com/envato/stack_master/blob/8ea5a0622deaeed49e20d2ce8defc671659d28e3/stack_master.gemspec#L26

**Comment by patrobinson** [comment]
Ah I noticed this the other day and I think you're right.

**Comment by patrobinson** [comment]
Sorry for the delay, I got sidetracked by another bug that I had trouble nailing down. This is fixed now in 1.8.2
