### ISSUE TITLE
Command options not passed through when args are present

### ISSUE THREAD

**Issue by rbayerl** [envato/stack_master#248]
When `commander` is bumped to `v4.4.6` commands do not respect global options when args are also passed in. It must be related to https://github.com/commander-rb/commander/pull/72, but I'm not sure why it only triggers when args are passed in. Possibly because of https://github.com/commander-rb/commander/pull/72/files#diff-f5bc2065042b5aadd9785fa959c5af93R163? I don't know much about `commander` (and maybe this issue should go to them). For now I will pin `commander` to `v4.4.5`, but if someone can point me in the right direction I will gladly submit a patch.

Note that this applies to all commands.

Working example (no args, just global options):
```
$ AWS_PROFILE=dev bundle exec stack_master apply -c foo.yml -n
Executing apply on foo in us-west-2
Stack diff:
--- /var/folders/7r/82zfp0bs31b9pvnnydnwhsw80000gp/T/diffy20180814-12420-1jtv6b3        2018-08-14 15:54:33.000000000 -0500
+++ /var/folders/7r/82zfp0bs31b9pvnnydnwhsw80000gp/T/diffy20180814-12420-ykgu2j 2018-08-14 15:54:33.000000000 -0500
@@ -0,0 +1,7 @@
+{
+  "Resources": {
+    "IamUser": {
+      "Type": "AWS::IAM::User"
+    }
+  }
+}
\ No newline at end of file
Parameters diff:
+--- {}
No stack found

========================================
Proposed change set:
Add AWS::IAM::User IamUser
========================================
Create stack (y/n)? n
Stack creation aborted
```
Not working example (when args are present):
```
$ AWS_PROFILE=dev bundle exec stack_master apply us-west-2 foo -c foo.yml -n
Failed to load config file stack_master.yml
```

**Comment by patrobinson** [comment]
Yep I noticed one of our tests started filling with 4.4.6 but I thought it was just a badly written test.

I think we should pin to <=4.4.5 and raise this upstream

**Comment by rbayerl** [comment]
:+1:
