### ISSUE TITLE
Parameters are named with underscores, but stacks are named with dashes

### ISSUE THREAD

**Issue by mipearson** [envato/stack_master#262]
Quoting the docs:

```

Parameters are loaded from multiple YAML files, merged from the following lookup paths from bottom to top:

parameters/[stack_name].yaml
parameters/[stack_name].yml
parameters/[region]/[underscored_stack_name].yaml
parameters/[region]/[underscored_stack_name].yml
parameters/[region_alias]/[underscored_stack_name].yaml
parameters/[region_alias]/[underscored_stack_name].yml
```

This is confusing when navigating your editor trying to find `foo-bar-baz` when you actually want `foo_bar_baz`, as in the main `stack_master.yml` it's defined with dashes.

I want to add parameter resolving that looks for dashes before underscores and make it the new default, perhaps deprecating underscore parameter files for StackMaster 2.

**Comment by mbklaene** [comment]
Agree! I spent an hour trying to figure this out when I decided to rename my stack and assumed the parameter file would match the template.
