### ISSUE TITLE
stack_master apply with no changes exits with non-zero

### ISSUE THREAD

**Issue by sergei-matheson** [envato/stack_master#277]
In version 1.13, `stack_master apply` exits with status code 1 if there are no changes. It also exits with status code 1 from `stack_master diff` if there are no changes. These are breaking changes in behaviour from previous versions.

In my opinion, while returning non-zero from a diff command with no changes makes sense, returning non-zero from an apply command with no changes does not. This would mean, in a CI/CD environment, that a build that deployed infrastructure would pass, and then a rebuild, with no changes, would fail. Obviously, there would be ways to work around this, but it seems counter-intuitive.

**Comment by patrobinson** [comment]
Related to https://github.com/envato/stack_master/pull/276

**Comment by grosser** [comment]
... or add that `puts caller` to `def failed` since that seems to be how errors are added
