### ISSUE TITLE
stack_master validate exits with non-zero on valid stack

### ISSUE THREAD

**Issue by orien** [envato/stack_master#278]
`stack_master validate` exits with a non-zero code on a valid stack.

```
> stack_master --version
StackMaster 1.13.0
echo $?
1

> stack_master validate us-east-1 bastion-vpc
Executing validate on bastion-vpc in us-east-1
bastion-vpc: valid
> echo $?
1
```

This causes a bit of havoc in continuous integration where we rely on the exit code to indicate the validity of the stack.

**Comment by orien** [comment]
This was potentially introduced in #276 and seems closely related to #277.

**Comment by logingood** [comment]
https://github.com/envato/stack_master/pull/279
