### ISSUE TITLE
Add IAM capability 'CAPABILITY_AUTO_EXPAND' to apply.rb

### ISSUE THREAD

**Issue by TheCrimsinGhost** [envato/stack_master#304]
Some template contain macros. Macros perform custom processing on templates; this can include simple actions like find-and-replace operations, all the way to extensive transformations of entire templates. Because of this, users typically create a change set from the processed template, so that they can review the changes resulting from the macros before actually updating the stack. If your stack template contains one or more macros, and you choose to update a stack directly from the processed template, without first reviewing the resulting changes in a change set, you must acknowledge this capability.

**Comment by TheCrimsinGhost** [comment]
Just a note this is a great app!

**Comment by patrobinson** [comment]
This should be a pretty trivial change if you want to give it a go or anyone else.
It's just a matter of adding the capability to the [stack options](https://github.com/envato/stack_master/blob/master/lib/stack_master/commands/apply.rb#L181) as well as the [test](https://github.com/envato/stack_master/blob/master/spec/stack_master/commands/apply_spec.rb#L52)

**Comment by TheCrimsinGhost** [comment]
I can take it, could you give me push access please?

**Comment by orien** [comment]
@TheCrimsinGhost feel free to fork this repository for write access to your own personal copy. From there you can make pull request.

**Comment by patrobinson** [comment]
Released in 2.2.0
