### ISSUE TITLE
colorize gem is GPL-2

### ISSUE THREAD

**Issue by klauern** [envato/stack_master#332]
In looking at the list of dependencies used with `stack_master`, the [`colorize`](https://rubygems.org/gems/colorize) gem is under a GPL-2 license.

In talking with some of my colleagues, the [`rainbow`](https://rubygems.org/gems/rainbow) gem would be a possible alternative, as it is MIT-licensed as well.

**Comment by orien** [comment]
Thanks for raising this issue @klauern.

Could you please describe the problems you're experiencing with the GNU General Public License V2?

**Comment by klauern** [comment]
By pulling in and using stack_master, it requires that we also pull in `colorize`, which implicitly means we have to adhere to GPLv2's licensing:

https://tldrlegal.com/license/gnu-general-public-license-v2

Whether your library is MIT or not, it sets up a dependency that puts the onus on consumers of your library to adhere to GPLv2.  At least, that is the rough guidance I am getting from legal and hence why it's an issue when we're using your library for any private use.

**Comment by orien** [comment]
For my own curiosity, are there specific terms of the license that are causing issues for your use-case, or has the legal simply deemed the license too risky and issued a general ban?

**Comment by klauern** [comment]
It's mostly around putting our use of this tool in a legal gray area.  We would have a couple options on our end to be compliant:

1. fork this repo, remove the library in use
2. get #333 merged in and have that change be applicable to all corporate use
3. go through a paperwork process to get this item excluded, and then circle back later to re-confirm periodically
4. move off of this tool (unlikely)

The simplest fix is *2*, where we can use a library that doesn't have the legal baggage that the other gem has, hence why we decided to throw that PR together.

**Comment by orien** [comment]
@klauern: I see you're at Zendesk. Could you please help get this PR merged? It's somewhat related. https://github.com/zendesk/zendesk_api_client_rb/pull/427

**Comment by klauern** [comment]
done.  Thank you sir
-Nick Klauer

**Comment by orien** [comment]
Awesome! :tada: Thank you.
