### ISSUE TITLE
Stack_master not getting installed on windows with Error as Failed to build gem native extension

### ISSUE THREAD

**Issue by ranapratap4312** [envato/stack_master#367]
Hi.
I am trying to install stack_master on my windows 10 Enterprise OS. Running below command.
gem install stack_master

C:\windows\system32>gem --version
3.3.3

Below is the error:
C:\windows\system32>gem install stack_master
Fetching aws-sdk-s3-1.111.2.gem
Fetching aws-sdk-ssm-1.128.0.gem
Fetching aws-sdk-ec2-1.295.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing stack_master:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/psych-3.3.2/ext/psych
C:/tools/ruby31/bin/ruby.exe -I C:/tools/ruby31/lib/ruby/3.1.0 -r ./siteconf20220124-19236-hwo96n.rb extconf.rb
checking for yaml.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/tools/ruby31/bin/$(RUBY_BASE_NAME)
        --with-libyaml-dir
        --without-libyaml-dir
        --with-libyaml-include
        --without-libyaml-include=${libyaml-dir}/include
        --with-libyaml-lib
        --without-libyaml-lib=${libyaml-dir}/lib
        --enable-bundled-libyaml
        --disable-bundled-libyaml
C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:624:in `block in try_compile'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:573:in `with_werror'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:624:in `try_compile'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:1213:in `block in find_header'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
        from C:/tools/ruby31/lib/ruby/3.1.0/mkmf.rb:1212:in `find_header'
        from extconf.rb:10:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/tools/ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/psych-3.3.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/psych-3.3.2 for inspection.
Results logged to C:/tools/ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/psych-3.3.2/gem_make.out

**Comment by orien** [comment]
It's failing to install the `psych` gem.

> The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first.

It looks like you don't have the necessary tools installed.

**Comment by ranapratap4312** [comment]
After installing Ruby+Devkit, issue got resolved.
Thanks
