### ISSUE TITLE
Feature request - Nested stacks creation

### ISSUE THREAD

**Issue by lethalpaga** [envato/stack_master#60]
At the moment stack_master cannot create nested stacks as it's supplying the template body to the API.
Do you have any plans to support that?

The way I see it :
- An S3 bucket URL and prefix would have to be added to the config file (global and per-region configuration)
- All nested templates would have to be declared alongside the main template, maybe as a `file` parameter (that would allow one to upload any kind of file to that bucket, if used by a UserData script or such) and uploaded to that bucket
- When creating the stack, pass in a `template_url` instead of a `template_body` parameter
- I'm not sure how the stack events would be handled. Worst case would be that only the events from the toplevel stack would be displayed (so not events from the nested stacks). I suppose it's good enough for a first version
- Stack deletion should work as-is as cfn takes care of the substack deletion
- Diffs, Output and Resources listing would only show the ones from the toplevel template. AFAIK there is no easy way to get substacks other that iterating over the Cloudformation::Stack resources recursively. Again I assume that would be acceptable in a first version.
- The `too_big?`method would need to know which method is used as the allowed size is different

Any thoughts on this? If not I'm happy to give a crack at this.

**Comment by stevehodgkiss** [comment]
Hi @lethalpaga 

It sounds like there are two parts to this

- allowing CF updates via S3
- nested stack support

We don't have any immediate plans to implement either, but we've discussed CF updates through S3 before. We don't use nested stacks and instead connect stacks together with stack outputs/parameter resolvers.

> All nested templates would have to be declared alongside the main template, maybe as a file parameter (that would allow one to upload any kind of file to that bucket, if used by a UserData script or such) and uploaded to that bucket

That sounds reasonable. Just thinking out load: I wonder if we could use parameter resolvers for this. For example:

```
nested_stack_url:
  nested_stack: template-name.rb
```

The resolver would automatically compile and upload the template and provide an S3 url. I'm not sure how diffing would work on nested stacks though.

Happy for you to have a go implementing this. Thanks!

**Comment by luckymike** [comment]
The SparkleFormation `nest!()` method will generate a nested stack resource (which includes a path to the template in the S3 Bucket). You would need to support configuring the bucket(s) to use (and providing these to SparkleFormation at compilation) and uploading templates to the bucket. 

This is implemented in [sfn](https://github.com/sparkleformation/sfn) if you'd like to see it in action to understand how the parts work.

**Comment by patrobinson** [comment]
We support S3 uploads now, I'm unsure if nested stacks are supported though. Feel free to open a new issue if there are any issues.
