### ISSUE TITLE
Numeric parameters not handled well

### ISSUE THREAD

**Issue by gstamp** [envato/stack_master#66]
When you pass a numeric parameter to Stack Master it blows up with something like this:

```
src/stack_master/lib/stack_master/parameter_resolver.rb:22:in `rescue in block in resolve': Unable to resolve parameter "AutoScalingGroupMinSize" value causing error: 2 (StackMaster::ParameterResolver::InvalidParameter)
```

A work around is to just convert those parameters to strings but it would be nice not to have to worry about this.

**Comment by stevehodgkiss** [comment]
This is fixed now.
