### ISSUE TITLE
sm status command continues to run status even if given invalid arguments

### ISSUE THREAD

**Issue by gstamp** [envato/stack_master#76]
It complains arguments are invalid but does not halt execution.

**Comment by stevehodgkiss** [comment]
I think we should allow status to be run like any other stack specific command can now be... filtered by stack, or not (no args == all). We just need to update it in cli to use execute_stacks_command and remove the error message.

**Comment by gstamp** [comment]
:+1:

**Comment by patrobinson** [comment]
This seems to work well now.
