### ISSUE TITLE
Add support for more template generators

### ISSUE THREAD

**Issue by stevehodgkiss** [envato/stack_master#81]
- YAML
- `cfndsl` - https://github.com/stevenjack/cfndsl

Any others?

**Comment by gstamp** [comment]
It might be nice to have JSON support with comments. Would need to find a library to strip them out I guess.

Another one might be just using plain old ERB?

**Comment by flyinbutrs** [comment]
If you want JSON support with comments, technically you can just use YAML.  An alternate syntax of YAML is actually just JSON + comments, so any YAML parser should be able to parse a JSON file with comments in it.

````ruby
[1] pry(main)> require 'yaml'
=> true
[2] pry(main)> test = "{\n#testing\n}"
=> "{\n#testing\n}"
[3] pry(main)> YAML.load(test)
=> {}
````

So yeah, +1 for YAML input. should be pretty trivial to add, I'll fork and see.

**Comment by neillturner** [comment]
cfndsl support would be really good as it is the most popular generator of cloudformation templates that is written in ruby. it should be really easier to integrate as it is just running cfndsl commands. 
I also use the ppjson to pretty print the generated cloudformation code. 

I've built alot of examples for cfndsl at https://github.com/neillturner/cfndsl_examples
and there is a utility to convert templates to cfndsl format that is very handy.

**Comment by thekindofme** [comment]
Hi @neillturner we have added basic CfnDsl template support with #99. However, this dose not add support for using cfndsl variables. How would you like that supported in SM? How would you imagine a user supply values for cfndsl variables when using a cfndsl template with SM?
