### ISSUE TITLE
provide provider support like terraform 

### ISSUE THREAD

**Issue by neillturner** [envato/stack_master#86]
Alot of corporates are starting to use terraform because it has support for non-AWS providers. This allows corporate to provision both AWS and non-AWS resources from the same terraform script. 
This is a killer feature for corporates because they other have non-AWS resources like their own DNS etc. 
I would be easy to add the ability to define providers into stackmaster and allow folks to write third party gems that can be hooked into stack master. This would be a real killer feature for you and allow you to compete with terraform.

**Comment by stevehodgkiss** [comment]
StackMaster is a wrapper specifically for CloudFormation. We have no plans to manage resources outside of CloudFormation, that would probably be an entirely new project separate to StackMaster.
